[package]
name = "firebase-sdk"
version = "0.1.0"
edition = "2021"
authors = ["Sayed Ali Sina Hussaini <s.alisinahussaini313@gmail.com>"]
description = "A complete Firebase SDK in Rust, with modular support for Authentication, Messaging, Firestore, Storage, and Realtime Database."
license = "MIT OR Apache-2.0"
repository = "https://github.com/real-ali/firebase-sdk"
readme = "README.md"
documentation = "https://docs.rs/firebase-sdk"
keywords = ["firebase", "sdk", "auth", "messaging", "firestore", "rust"]
categories = ["api-bindings", "authentication", "web-programming", "database"]

[dependencies]
firebase-core = { path = "../crates/firebase-core" }
firebase-authentication = { path = "../crates/firebase-authentication" }
firebase-firestore = { path = "../crates/firebase-firestore" }
firebase-messaging = { path = "../crates/firebase-messaging" }
firebase-realtime-db = { path = "../crates/firebase-realtime-db" }
firebase-storage = { path = "../crates/firebase-storage" }
