[package]
name = "firebase-sdk"
version = "0.1.0"
edition = "2021"
authors = ["Sayed Ali Sina Hussaini <s.alisinahussaini313@gmail.com>"]
description = "A complete Firebase SDK in Rust, with modular support for Authentication, Messaging, Firestore, Storage, and Realtime Database."
license = "MIT OR Apache-2.0"
repository = "https://github.com/real-ali/firebase-sdk"
readme = "README.md"
documentation = "https://docs.rs/firebase-sdk"
keywords = ["firebase", "sdk", "auth", "messaging", "firestore"]
categories = ["api-bindings", "authentication", "web-programming", "database"]

[dependencies]
firebase-core = "0.1"
firebase-authentication = "0.1"
firebase-firestore = "0.1"
firebase-messaging = "0.1"
firebase-realtime-db = "0.1"
firebase-store = "0.1"
